### ISSUE TITLE
can not install ?

### ISSUE THREAD

**Issue by vince67** [maxmind/geoip-api-python#19]
Both pip install GeoIP and install from source
(GeoIP-1.3.2)

GOT THIS FATAL ERROR:

py_GeoIP.c:21:20: fatal error: Python.h: No such file or directory

 #include <Python.h>  
                             ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by archever** [comment]
i got this error too, how did you deal with this?

**Comment by oschwald** [comment]
This is likely caused by not having the development package for Python installed. For instance, on Ubuntu, you would need to install `python3-dev` or `python2.7-dev`.

**Comment by ParasolKao** [comment]
If your os is centos7,you can try: `yum install python-devel`
