### ISSUE TITLE
py_GeoIP.c:23:19: fatal error: GeoIP.h: No such file or directory

### ISSUE THREAD

**Issue by supahal** [maxmind/geoip-api-python#20]
Hi,

Im so sorry. I can't build the package. I dont find the header file. 

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
running build
running build_ext
building 'GeoIP' extension
creating build
creating build/temp.linux-i686-2.7
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c py_GeoIP.c -o build/temp.linux-i686-2.7/py_GeoIP.o -fno-strict-aliasing
py_GeoIP.c:23:19: fatal error: GeoIP.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by oschwald** [comment]
You need to install [libGeoIP](https://github.com/maxmind/geoip-api-c) first.

**Comment by ItzGerald** [comment]
C:\Users\ASUS_01\Desktop\ufonet-master>pip install geoip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Ple
ase upgrade your Python as Python 2.7 won't be maintained after that date. A fut
ure version of pip will drop support for Python 2.7.
Collecting geoip
  Using cached https://files.pythonhosted.org/packages/f2/7b/a463b7c3df8ef4b9c92
906da29ddc9e464d4045f00c475ad31cdb9a97aae/GeoIP-1.3.2.tar.gz
Installing collected packages: geoip
  Running setup.py install for geoip ... error
    ERROR: Complete output from command 'c:\python27\python.exe' -u -c 'import s
etuptools, tokenize;__file__='"'"'c:\\users\\asus_01\\appdata\\local\\temp\\pip-
install-ux15tw\\geoip\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(_
_file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(comp
ile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\asus_01\appdata
\local\temp\pip-record-c83vbn\install-record.txt' --single-version-externally-ma
naged --compile:
    ERROR: c:\python27\lib\distutils\dist.py:267: UserWarning: Unknown distribut
ion option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'GeoIP' extension
    creating build
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    C:\Users\ASUS_01\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pyth
on\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\in
clude -Ic:\python27\PC /Tcpy_GeoIP.c /Fobuild\temp.win-amd64-2.7\Release\py_GeoI
P.obj -fno-strict-aliasing
    cl : Command line warning D9002 : ignoring unknown option '-fno-strict-alias
ing'
    py_GeoIP.c
    py_GeoIP.c(23) : fatal error C1083: Cannot open include file: 'GeoIP.h': No
such file or directory
    error: command 'C:\\Users\\ASUS_01\\AppData\\Local\\Programs\\Common\\Micros
oft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status
 2
    ----------------------------------------
ERROR: Command "'c:\python27\python.exe' -u -c 'import setuptools, tokenize;__fi
le__='"'"'c:\\users\\asus_01\\appdata\\local\\temp\\pip-install-ux15tw\\geoip\\s
etup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().r
eplace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"
'exec'"'"'))' install --record 'c:\users\asus_01\appdata\local\temp\pip-record-c
83vbn\install-record.txt' --single-version-externally-managed --compile" failed
with error code 1 in c:\users\asus_01\appdata\local\temp\pip-install-ux15tw\geoi
p\

**Comment by oschwald** [comment]
@ItzGerald, similar to the above request, it sounds like libGeoIP is not available. You need to install this and make sure the compile can find the header and object files.

That said, I would recommend using `geoip2` at this point.
