### ISSUE TITLE
warning: no files found matching 'ChangeLog'

### ISSUE THREAD

**Issue by Geyup** [maxmind/geoip-api-python#21]
When compiling 1.3.2 the command line spits out this message;

```warning: no files found matching 'ChangeLog'```

It appears it doesn't like it as ```ChangeLog.md``` in the source.

**Comment by oschwald** [comment]
Thanks. This is fixed in 69e46ee. You can safely ignore the warning.

**Comment by Geyup** [comment]
Yeah I figured harmless, but wanted to report it to you, keep that code clean... hehe :)
