### ISSUE TITLE
Question: Any Security Reason For Python3?

### ISSUE THREAD

**Issue by Geyup** [maxmind/geoip-api-python#22]
I hope you don't mind a question here?

Is there any reason to switch to the latest 1.3.2 for any security reasons?

I'm only going to use GeoIP for the P2P app nicotine;

https://github.com/eLvErDe/nicotine-plus

I'm using at present GeoIP 1.6.7, so not sure if there's any real benefit from 1.2.9 to 1.3.2, in regards to what I'm doing here?

Thank you very much for your time and help.

**Comment by oschwald** [comment]
I think there was a segfault that was fixed. Otherwise, it was mostly updates for Python 3. That said, 1.3.2 should be completely compatible with any code that worked with 1.2.9.

**Comment by Geyup** [comment]
Well nicotine is a python2 app, so not sure there could even be any conflict using 1.3.2 as a python3 version, was another thought in my head... 

So I'm just trying to figure if I have python2 on my box, any reason to switch?

hmm

thanks again

**Comment by Geyup** [comment]
Sorry, forgot to ask, can 1.3.2 be built against python2 as well? Because I ran it that way and it seems to of compiled and working with nicotine...

If I compile it as python3 nicotine doesn't except it...

This is my pkg contents of 1.3.2 against Python2;

```
FILE LIST:
./
install/
install/slack-desc
usr/
usr/lib64/
usr/lib64/python2.7/
usr/lib64/python2.7/site-packages/
usr/lib64/python2.7/site-packages/GeoIP.so
usr/lib64/python2.7/site-packages/GeoIP-1.3.2-py2.7.egg-info/
usr/lib64/python2.7/site-packages/GeoIP-1.3.2-py2.7.egg-info/SOURCES.txt
usr/lib64/python2.7/site-packages/GeoIP-1.3.2-py2.7.egg-info/dependency_links.txt
usr/lib64/python2.7/site-packages/GeoIP-1.3.2-py2.7.egg-info/PKG-INFO
usr/lib64/python2.7/site-packages/GeoIP-1.3.2-py2.7.egg-info/top_level.txt
usr/doc/
usr/doc/GeoIP-Python-1.3.2/
usr/doc/GeoIP-Python-1.3.2/MANIFEST
usr/doc/GeoIP-Python-1.3.2/LICENSE
usr/doc/GeoIP-Python-1.3.2/GeoIP-Python.SlackBuild
usr/doc/GeoIP-Python-1.3.2/README
usr/doc/GeoIP-Python-1.3.2/ChangeLog
```

thank you again

**Comment by Geyup** [comment]
Sorry I guess this still holds true for 1.3.2;

```
Requirements

    Python 2.5+ or 3.3+
    GeoIP Legacy C Library 1.4.7 or greater
```
