### ISSUE TITLE
'pip install GeoIP' fails on macOS: fatal error: 'GeoIP.h' file not found

### ISSUE THREAD

**Issue by valeriyvan** [maxmind/geoip-api-python#24]
pip install GeoIP
Collecting GeoIP
  Using cached GeoIP-1.3.2.tar.gz
Installing collected packages: GeoIP
  Running setup.py install for GeoIP ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/q0/xwxj618x4cg28pskym3_b4k40000gp/T/pip-build-OFQtlJ/GeoIP/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/q0/xwxj618x4cg28pskym3_b4k40000gp/T/pip-ebv2nX-record/install-record.txt --single-version-externally-managed --compile:
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'GeoIP' extension
    creating build
    creating build/temp.macosx-10.6-intel-2.7
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c py_GeoIP.c -o build/temp.macosx-10.6-intel-2.7/py_GeoIP.o -fno-strict-aliasing
    py_GeoIP.c:23:10: fatal error: 'GeoIP.h' file not found
    #include "GeoIP.h"
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/q0/xwxj618x4cg28pskym3_b4k40000gp/T/pip-build-OFQtlJ/GeoIP/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/q0/xwxj618x4cg28pskym3_b4k40000gp/T/pip-ebv2nX-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/q0/xwxj618x4cg28pskym3_b4k40000gp/T/pip-build-OFQtlJ/GeoIP/

**Comment by oschwald** [comment]
You need `libGeoIP` (and its header files) installed to use this library.

**Comment by TomDobbs** [comment]
I still have the exact same problem as above. 

Ran the below to try to help, but still no help.
brew install libGeoIP
Warning: geoip-1.6.10 already installed
