### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by FrnkVieira** [maxmind/geoip-api-python#25]
As it seems "MODE_MMAP_EXT" is not supported when using Python 3.6
There are any plans to release it ?

**Comment by oschwald** [comment]
Did you mean to open this issue for the [`geoip2` module](https://github.com/maxmind/GeoIP2-python)? This repo is for the legacy `GeoIP` module, which I don't believe has that flag. As for `geoip2`, the extension should work fine on 3.6. Please include details about the failure you are seeing if you open an issue there.
