### ISSUE TITLE
cannot install pip geoip!

### ISSUE THREAD

**Issue by azamet90** [maxmind/geoip-api-python#27]
```
sudo pip install geoip
Collecting geoip
  Using cached https://files.pythonhosted.org/packages/f2/7b/a463b7c3df8ef4b9c92906da29ddc9e464d4045f00c475ad31cdb9a97aae/GeoIP-1.3.2.tar.gz
  Running setup.py (path:/tmp/pip-install-Gu5vyc/geoip/setup.py) egg_info for package geoip produced metadata for project name geoIp. Fix your #egg=geoip fragments.                                                            
Building wheels for collected packages: geoIp, geoIp
  Running setup.py bdist_wheel for geoIp ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Gu5vyc/geoip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-d4TgHm --python-tag cp27:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_ext
  building 'GeoIP' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-07FOaN/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c py_GeoIP.c -o build/temp.linux-x86_64-2.7/py_GeoIP.o -fno-strict-aliasing
  py_GeoIP.c:23:10: fatal error: GeoIP.h: Böyle bir dosya ya da dizin yok
     23 | #include "GeoIP.h"
        |          ^~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for geoIp
  Running setup.py clean for geoIp
  Running setup.py bdist_wheel for geoIp ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Gu5vyc/geoip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-7_QeFg --python-tag cp27:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_ext
  building 'GeoIP' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-07FOaN/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c py_GeoIP.c -o build/temp.linux-x86_64-2.7/py_GeoIP.o -fno-strict-aliasing
  py_GeoIP.c:23:10: fatal error: GeoIP.h: Böyle bir dosya ya da dizin yok
     23 | #include "GeoIP.h"
        |          ^~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for geoIp
  Running setup.py clean for geoIp
Failed to build geoIp geoIp
Installing collected packages: geoIp
  Running setup.py install for geoIp ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Gu5vyc/geoip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2WSvBi/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'GeoIP' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-07FOaN/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c py_GeoIP.c -o build/temp.linux-x86_64-2.7/py_GeoIP.o -fno-strict-aliasing
    py_GeoIP.c:23:10: fatal error: GeoIP.h: Böyle bir dosya ya da dizin yok
       23 | #include "GeoIP.h"
          |          ^~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Gu5vyc/geoip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2WSvBi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-Gu5vyc/geoip/
```

**Comment by oschwald** [comment]
The `libGeoIP` C library is needed to install this package. However, I would recommend against using this package and using `geoip2` instead.

**Comment by FrankensteinEvil0069** [comment]
How to download the libGeoIP and where can i gwt the tar.gz file download for libGeoIP

**Comment by horgh** [comment]
You can get it from https://github.com/maxmind/geoip-api-c. See https://github.com/maxmind/geoip-api-c/releases.

**Comment by FrankensteinEvil0069** [comment]
> You can get it from https://github.com/maxmind/geoip-api-c. See https://github.com/maxmind/geoip-api-c/releases.

Thanks so much it worked finally after installing the tar.gz file from here  **https://github.com/maxmind/geoip-api-c/releases.**
then cd into it allowing all the permissions by (chmod +x *) then typing 
./configure
make
make install
then cd into GeoIP1.3.2 file and allowing by (chmod +x *) then typing sudo python3 setup.py install 


root@shreyas-kali-linux:~/Downloads/GeoIP-1.3.2# sudo python3 setup.py install
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
Warning: 'classifiers' should be a list, got type 'tuple'
running install
running bdist_egg
running egg_info
writing GeoIP.egg-info/PKG-INFO
writing dependency_links to GeoIP.egg-info/dependency_links.txt
writing top-level names to GeoIP.egg-info/top_level.txt
reading manifest file 'GeoIP.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'ChangeLog'
writing manifest file 'GeoIP.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'GeoIP' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c py_GeoIP.c -o build/temp.linux-x86_64-3.9/py_GeoIP.o
creating build/lib.linux-x86_64-3.9
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/py_GeoIP.o -lGeoIP -o build/lib.linux-x86_64-3.9/GeoIP.cpython-39-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.9/GeoIP.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for GeoIP.cpython-39-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/GeoIP.py to GeoIP.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying GeoIP.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying GeoIP.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying GeoIP.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying GeoIP.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.GeoIP.cpython-39: module references __file__
creating dist
creating 'dist/GeoIP-1.3.2-py3.9-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing GeoIP-1.3.2-py3.9-linux-x86_64.egg
removing '/usr/local/lib/python3.9/dist-packages/GeoIP-1.3.2-py3.9-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.9/dist-packages/GeoIP-1.3.2-py3.9-linux-x86_64.egg
Extracting GeoIP-1.3.2-py3.9-linux-x86_64.egg to /usr/local/lib/python3.9/dist-packages
GeoIP 1.3.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.9/dist-packages/GeoIP-1.3.2-py3.9-linux-x86_64.egg
Processing dependencies for GeoIP==1.3.2
Finished processing dependencies for GeoIP==1.3.2
