### ISSUE TITLE
Upload wheels for Python 2

### ISSUE THREAD

**Issue by abitrolly** [maxmind/geoip-api-python#28]
I need to run [the legacy code](https://github.com/osm-by/OpenStreetMap.by) that uses GeoIP, and I have problems getting all the dependencies (gcc and libs) for GeoIP right. Is it possible to upload wheels for Python2 to PyPI?

**Comment by oschwald** [comment]
This library is in maintenance mode and supporting wheels packages for all the supported platforms would take considerable effort. It is unlikely that this will be done in the near future.

**Comment by abitrolly** [comment]
@oschwald it it not complicated at all with this package - https://cibuildwheel.readthedocs.io/en/stable/setup/#travis-ci

**Comment by oschwald** [comment]
Given that the legacy databases have an [EOL date set](https://blog.maxmind.com/2020/06/01/retirement-of-geoip-legacy-downloadable-databases-in-may-2022/), it seems unlikely we will make enhancements to our release process such as this. This is something we could consider for the `maxminddb` package used for the GeoIP2 databases though.
