### ISSUE TITLE
MacOs Install Fail

### ISSUE THREAD

**Issue by RocketNinja15** [maxmind/geoip-api-python#31]
I am installing using pip3 install geoip or sudo pip3 install geoip. I get this that makes it fail.

   ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-k23lgxdu/geoip/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-k23lgxdu/geoip/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-e5rjznon/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/GeoIP
         cwd: /private/tmp/pip-install-k23lgxdu/geoip/
    Complete output (15 lines):
    /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Warning: 'classifiers' should be a list, got type 'tuple'
    running install
    running build
    running build_ext
    building 'GeoIP' extension
    creating build
    creating build/temp.macosx-10.9-x86_64-3.9
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c py_GeoIP.c -o build/temp.macosx-10.9-x86_64-3.9/py_GeoIP.o
    py_GeoIP.c:23:10: fatal error: 'GeoIP.h' file not found
    #include "GeoIP.h"
             ^~~~~~~~~
    1 error generated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-k23lgxdu/geoip/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-k23lgxdu/geoip/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-e5rjznon/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/GeoIP Check the logs for full command output.

**Comment by RocketNinja15** [comment]
> This appears to be an issue with our legacy `GeoIP` package rather the `geoipupdate`. I am moving the issue there.
> 
> As far as your particular issue goes, you need to have `libGeoIP` and the associated header files installed.

how can I install libgeoip. pip3 install libgeoip?

**Comment by oschwald** [comment]
It is probably easiest to install it with [Homebrew](https://formulae.brew.sh/formula/geoip) on macOS. Otherwise, see [the installation directions](https://github.com/maxmind/geoip-api-c).

**Comment by RocketNinja15** [comment]
@oschwald It says its installed...
brew install geoip

Warning: geoip 1.6.12 is already installed and up-to-date
To reinstall 1.6.12, run `brew reinstall geoip`

**Comment by RocketNinja15** [comment]
> It is probably easiest to install it with [Homebrew](https://formulae.brew.sh/formula/geoip) on macOS. Otherwise, see [the installation directions](https://github.com/maxmind/geoip-api-c).

how do I install on windows?

**Comment by oschwald** [comment]
I would suggest using `geoip2` with the newer `mmdb` databases. The `dat` databases will be EOL in a little over a year. `geoip2` should be much easier to get running on Windows.

If that is not an option, you may consider using `pygeoip`, which is pure Python and should work well on Windows.

Although it might be possible to install `GeoIP` on Windows, we don't have directions or a guide on how to do it.
