### ISSUE TITLE
GeoIP.c:23:10: fatal error: GeoIP.h: No such file or directory    23 | #include "GeoIP.h"while trying to install GeoIP package for python PART 2

### ISSUE THREAD

**Issue by FrankensteinEvil0069** [maxmind/geoip-api-python#34]
I want install this python dependency (GeoIP) for one of my tools. I installed GeoIP-1.3.2 from here https://pypi.org/project/GeoIP/#files  and i'm getting this error again and again when im writing this code "sudo python3 setup.py install"
and im getting this error 
root@shreyas-kali-linux:~/Downloads/GeoIP-1.3.2# sudo python3 setup.py install
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
Warning: 'classifiers' should be a list, got type 'tuple'
running install
running bdist_egg
running egg_info
writing GeoIP.egg-info/PKG-INFO
writing dependency_links to GeoIP.egg-info/dependency_links.txt
writing top-level names to GeoIP.egg-info/top_level.txt
reading manifest file 'GeoIP.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'ChangeLog'
writing manifest file 'GeoIP.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'GeoIP' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c py_GeoIP.c -o build/temp.linux-x86_64-3.9/py_GeoIP.o
py_GeoIP.c:23:10: fatal error: GeoIP.h: No such file or directory
   23 | #include "GeoIP.h"
      |          ^~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
PLEASE HELP I NEED THAT TOOL VERY BADLY

**Comment by horgh** [comment]
Do you have the C library installed? https://github.com/maxmind/geoip-api-c. It's needed for this module.

As well, this module is end of life. It'd be best to use https://github.com/maxmind/GeoIP2-python if possible these days.

**Comment by FrankensteinEvil0069** [comment]
NO ,a tool  Ufonet-v1.6 requires only GeoIP-1.3.2, and YES I've tried this 
------------------------------------
Do you have the C library installed? https://github.com/maxmind/geoip-api-c. It's needed for this module.

As well, this module is end of life. It'd be best to use https://github.com/maxmind/GeoIP2-python if possible these days.
--------------------------------------
BUT IT DOSENT HELP, PLEASE GIVE ME A WAY TO FIX GeoIP-1.3.2 FATAL ERROR PROBLEM, PLEASE

**Comment by FrankensteinEvil0069** [comment]
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
_ufonet 1.6 requires GeoIP>=1.3.2, which is not installed_.**

**Comment by horgh** [comment]
It does sound like you need to install https://github.com/maxmind/geoip-api-c. The build isn't finding the header from that library.
